name = "recallai-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "recallai-memory"
database_id = "83370e35-38f9-40f2-a7e8-85e3b625ef9c"
migrations_dir = "migrations"
